### ISSUE TITLE
Method 'WriteCode' does not have an implementation.

### ISSUE THREAD

**Issue by JohnGoldInc** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#95] opened 2020-01-05 01:10 UTC
Getting following error on TargetFramework netcoreapp3.1; any ideas?

Method 'WriteCode' in type 'EntityFrameworkCore.Scaffolding.Handlebars.NullCSharpDbContextGenerator' from assembly 'EntityFrameworkCore.Scaffolding.Handlebars, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b10b51e7b9be6a2e' does not have an implementation.

   at Microsoft.EntityFrameworkCore.Design.ServiceCollectionExtensions.AddHandlebarsScaffolding(IServiceCollection services, Action`1 configureOptions)
   at ScaffoldingDesignTimeServices.ConfigureDesignTimeServices(IServiceCollection services) in F:\NTSB\NTSB.data\ScaffoldingDesignTimeServices.cs:line 8
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureDesignTimeServices(Type designTimeServicesType, IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureUserServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

**Comment by ErikEJ** [comment] 2020-01-05 12:46
Duplicate of #94

**Closed** 2020-01-06 02:51 UTC
