### ISSUE TITLE
[Bug] Cannot run reverse engineering in ef core 6 with handlebars

### ISSUE THREAD

**Issue by sssHty** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#187] opened 2021-11-17 03:37 UTC
using package
EntityFrameworkCore.Scaffolding.Handlebars Version="3.8.5" 
Microsoft.EntityFrameworkCore Version="6.0.0"
Microsoft.EntityFrameworkCore.SqlServer Version="6.0.0"
Microsoft.EntityFrameworkCore.Design Version="6.0.0"
Microsoft.EntityFrameworkCore.Tools Version="6.0.0" 
dotnet ef --version
Entity Framework Core .NET Command-line Tools
6.0.0
run commond line
dotnet ef dbcontext scaffold "connectionString" Microsoft.EntityFrameworkCore.SqlServer
Build started...
Build succeeded.
**_System.TypeLoadException: Method 'WriteCode' in type_** 'EntityFrameworkCore.Scaffolding.Handlebars.NullCSharpEntityTypeGenerator' from assembly 'EntityFrameworkCore.Scaffolding.Handlebars, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b10b51e7b9be6a2e' does not have an implementation.

**Comment by tonysneed** [comment] 2021-11-24 16:06
Closing a duplicate of #181. Support for EF Core 6 will be added in the very near future.

**Closed by tonysneed** 2021-11-24 16:06 UTC
Labels: bug
