### ISSUE TITLE
Property names with special characters (ä,ö,ü) are converted to unicode strings

### ISSUE THREAD

**Issue by skriebi** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#30] opened 2018-07-18 10:06 UTC
Hello,

some of the columns in our database contains special characters (ä,ö,ü).
The characters are converted to `&#228;`, `&#246;` or `&#252;` unicode strings.

To solve the issue for me, I have created a hbs-helper, which simple writes the property-name with the WriteSafeString-Method of the TextWriter.

Helper registration:
```csharp
    public void ConfigureDesignTimeServices(IServiceCollection services)
    {
        var options = ReverseEngineerOptions.DbContextAndEntities;
        services.AddHandlebarsScaffolding(options);
        
        Handlebars.RegisterHelper("f-pn", FormatPropertyName);
    }

    void FormatPropertyName(TextWriter writer, object context, object[] args)
    {
        writer.WriteSafeString(args[0].ToString());
    }
```
Usage in templates:
`{{f-pn property-name}}`

I think, the property-name template should use the WriteSafeString-Method.

**Comment by tonysneed** [comment] 2018-07-20 23:27
You should add your helper like so:

```csharp
services.AddHandlebarsHelpers(myHelper);
```

See [here](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/sample/ScaffoldingSample/ScaffoldingDesignTimeServices.cs).

> I think, the property-name template should use the WriteSafeString-Method.

Perhaps you should open an issue on [Handlebars.Net](https://github.com/rexm/Handlebars.Net), since the templates should use `WriteSafeString`?  I recommend that, because it would solve the problem of special characters globally.

**Comment by ErikEJ** [comment] 2018-07-31 20:04
Reported here: https://github.com/ErikEJ/EFCorePowerTools/issues/77

**Comment by ErikEJ** [comment] 2018-07-31 20:05
EF Core team (and I) use UTF8 encoding...

**Comment by tonysneed** [comment] 2018-12-17 20:13
@ErikEJ What do you think I should do to fix this?

**Comment by ErikEJ** [comment] 2018-12-18 09:49
It looks like a Handlebars issue to me...
https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/src/EntityFrameworkCore.Scaffolding.Handlebars/Internal/FileSystemFileService.cs#L65

**Comment by tonysneed** [comment] 2018-12-27 20:44
Confirmed this is a Handlebars.Net issue. There needs to be a way to suppress HTML encoding. See [Issue 276](https://github.com/rexm/Handlebars.Net/issues/276) there.

**Comment by tonysneed** [comment] 2019-07-17 17:02
Closing, as this needs to be fixed by Handlebars.NET.

**Comment by tonysneed** [comment] 2021-09-08 15:56
Re-opening, as this [issue](https://github.com/Handlebars-Net/Handlebars.Net/issues/276) was fixed in [v2](https://github.com/Handlebars-Net/Handlebars.Net/releases/tag/2.0.0-preview-2) of [Handlebars.Net](https://github.com/Handlebars-Net/Handlebars.Net).

**Comment by Varorbc** [comment] 2021-09-24 12:38
If this option is not checked, Chinese will not be encoded.

![image](https://user-images.githubusercontent.com/5714438/134626956-f6beaed6-94ac-4f0c-bdda-fa5469f91094.png)

**Comment by ErikEJ** [comment] 2021-09-24 12:43
The option is: Use Data Annotations

**Comment by Varorbc** [comment] 2021-09-24 12:46
In addition, it is strange that some Chinese is not encoded

**Comment by Varorbc** [comment] 2021-09-24 12:57
In my investigation, I found that some Chinese are not encoded because `SuppressEncoding` is `true`, because I am not familiar with this project and do not know where to assign `SuppressEncoding`

https://github.com/Handlebars-Net/Handlebars.Net/blob/ad5c616c58397c6d52507c859cb9f1b397580e3a/source/Handlebars/IO/EncodedTextWriter.cs#L48-L57

**Comment by tonysneed** [comment] 2021-09-24 12:59
This flag was added in Handlebars.Net in v 2 and defaults to `true`. I think we just need to set it to `false`.

**Comment by tonysneed** [comment] 2021-09-24 13:12
I am wondering how to reproduce the encoding issue on my side. @Varorbc, @ErikEJ Any tips?

**Comment by Varorbc** [comment] 2021-09-24 13:12
Not so.This flag already exists in Handlebar. Net in V1.I think we should find out why some Chinese `SuppressEncoding` is `false` and some Chinese `SuppressEncoding` is `true` instead of directly modifying the default value

**Comment by tonysneed** [comment] 2021-09-24 14:08
@Varorbc I think the setting is `NoEscape`.  According to [issue 276](https://github.com/Handlebars-Net/Handlebars.Net/issues/276) in Handlebars.Net, support for `noEscape` was added to Handlebars.Net with [PR 375](https://github.com/Handlebars-Net/Handlebars.Net/pull/375) in [2.0.0-preview-2](https://github.com/Handlebars-Net/Handlebars.Net/releases/tag/2.0.0-preview-2). I will look into how we can set this to `true`.

**Comment by tonysneed** [comment] 2021-09-24 15:50
@Varorbc Please pull down PR #178 and test to see if it resolves encoding issues.

**Closed** 2021-12-23 02:52 UTC
Labels: bug
